{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "type": "structured",
        "name": "VK-SXD0E-002;Reporting_PAI",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "vk-sxd0e-002",
            "database": "Reporting_PAI"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "vk-sxd0e-002;Reporting_PAI",
          "Username": "axel.hjelmervik.hansen@ks.no",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Alle Data",
        "isHidden": true,
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "sourceColumn": "Tabell"
          },
          {
            "name": "Kommunenummer",
            "dataType": "string",
            "sourceColumn": "Kommunenummer"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel"
          },
          {
            "name": "Kjønnkode",
            "dataType": "string",
            "sourceColumn": "Kjønnkode"
          },
          {
            "name": "Kompetansenivåkode",
            "dataType": "string",
            "sourceColumn": "Kompetansenivåkode"
          },
          {
            "name": "Sektorkode",
            "dataType": "string",
            "sourceColumn": "Sektorkode"
          },
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi"
          },
          {
            "name": "Turnuskode",
            "dataType": "string",
            "sourceColumn": "Turnuskode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    #\"dbo_Alle Data\" = Source{[Schema=\"dbo\",Item=\"Alle Data\"]}[Data]",
                "in",
                "    #\"dbo_Alle Data\""
              ]
            }
          }
        ]
      },
      {
        "name": "Kjønn",
        "columns": [
          {
            "name": "Kjønnkode",
            "dataType": "string",
            "sourceColumn": "Kjønnkode"
          },
          {
            "name": "Kjønnnavn",
            "dataType": "string",
            "sourceColumn": "Kjønnnavn"
          },
          {
            "name": "KjønnkodeNavn",
            "dataType": "string",
            "sourceColumn": "KjønnkodeNavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    dbo_Kjønn = Source{[Schema=\"dbo\",Item=\"Kjønn\"]}[Data]",
                "in",
                "    dbo_Kjønn"
              ]
            }
          }
        ]
      },
      {
        "name": "Kompetansenivå",
        "columns": [
          {
            "name": "Kompetansenivåkode",
            "dataType": "string",
            "sourceColumn": "Kompetansenivåkode"
          },
          {
            "name": "Kompetansenivånavn",
            "dataType": "string",
            "sourceColumn": "Kompetansenivånavn"
          },
          {
            "name": "KompetansenivåkodeNavn",
            "dataType": "string",
            "sourceColumn": "KompetansenivåkodeNavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    dbo_Kompetansenivå = Source{[Schema=\"dbo\",Item=\"Kompetansenivå\"]}[Data]",
                "in",
                "    dbo_Kompetansenivå"
              ]
            }
          }
        ]
      },
      {
        "name": "PAI Indikatorer",
        "columns": [
          {
            "name": "Indikatorer",
            "dataType": "int64",
            "sourceColumn": "Indikatorer"
          },
          {
            "name": "Heltidsandel",
            "dataType": "int64",
            "sourceColumn": "Heltidsandel"
          },
          {
            "name": "Stillingsstørrelse",
            "dataType": "int64",
            "sourceColumn": "Stillingsstørrelse"
          },
          {
            "name": "Årsverk",
            "dataType": "int64",
            "sourceColumn": "Årsverk"
          },
          {
            "name": "Ansatte",
            "dataType": "int64",
            "sourceColumn": "Ansatte"
          },
          {
            "name": "Turnover",
            "dataType": "int64",
            "sourceColumn": "Turnover"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    #\"dbo_PAI Indikatorer\" = Source{[Schema=\"dbo\",Item=\"PAI Indikatorer\"]}[Data]",
                "in",
                "    #\"dbo_PAI Indikatorer\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Stillingsstørrelse, administrasjon",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Administrasjon\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, annet",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Annet\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, alle sektorer, ufilter",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, administrasjon, ufilter",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Administrasjon\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, annet, ufilter",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Annet\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, barnehage, ufilter",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Barnehage\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, helse/pleie/omsorg, ufilter",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, samferdsel og teknikk, ufilter",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Samferdsel og teknikk\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, undervisning, ufilter",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Undervisning\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, i alt",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Årsverk alt",
            "expression": [
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Årsverk\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse alt",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Stillingsstørrelse\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel alt",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Heltidsandel\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, barnehage",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Barnehage\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, helse/pleie/omsorg",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, samferdsel og teknikk",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Samferdsel og teknikk\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, undervisning",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Undervisning\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, i alt",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, faglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Faglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, høyere utdanning",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Høyere utdanning\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, ufaglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Ufaglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, kvinner",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, menn",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Ansatte alt",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI04\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ansatte\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, i alt",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, administrasjon",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Administrasjon\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, annet",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Annet\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, barnehage",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Barnehage\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, helse/pleie/omsorg, turnus",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Turnus\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, helse/pleie/omsorg",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, samferdsel og teknikk",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Samferdsel og teknikk\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, undervisning",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Undervisning\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, faglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Faglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, høyere utdanning",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Høyere utdanning\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, ufaglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Ufaglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, kvinner",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Antall ansatte, menn",
            "expression": [
              "",
              "",
              "CALCULATE([Ansatte alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, i alt",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, administrasjon",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Administrasjon\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, annet",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Annet\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, barnehage",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Barnehage\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, helse/pleie/omsorg",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, samferdsel og teknikk",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Samferdsel og teknikk\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, undervisning",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Undervisning\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, faglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Faglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, høyere utdanning",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Høyere utdanning\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, ufaglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Ufaglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, kvinner",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, menn",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Turnover alt",
            "expression": [
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI05\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Turnover\")",
              ")"
            ]
          },
          {
            "name": "Turnover, i alt",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\")",
              ")"
            ]
          },
          {
            "name": "Turnover, administrasjon",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Administrasjon\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, annet",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Annet\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, barnehage",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Barnehage\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, helse/pleie/omsorg",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, samferdsel og teknikk",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Samferdsel og teknikk\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, undervisning",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Undervisning\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, faglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Faglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, høyere utdanning",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Høyere utdanning\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, ufaglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Ufaglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, kvinner",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, menn",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Turnover, helse/pleie/omsorg, turnus",
            "expression": [
              "",
              "",
              "CALCULATE([Turnover alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Turnus\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, administrasjon",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Administrasjon\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, annet",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Annet\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, barnehage",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Barnehage\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, helse/pleie/omsorg",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, samferdsel og teknikk",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Samferdsel og teknikk\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, undervisning",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Undervisning\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, faglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Faglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, høyere utdanning",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Høyere utdanning\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, ufaglærte",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Ufaglærte\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, kvinner",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, menn",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"I alt\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Alle\")",
              ")"
            ]
          },
          {
            "name": "Heltidsandel, helse/pleie/omsorg, turnus",
            "expression": [
              "",
              "",
              "CALCULATE([Heltidsandel alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Turnus\")",
              ")"
            ]
          },
          {
            "name": "Stillingsstørrelse, helse/pleie/omsorg, turnus",
            "expression": [
              "",
              "",
              "CALCULATE([Stillingsstørrelse alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Turnus\")",
              ")"
            ]
          },
          {
            "name": "Årsverk, helse/pleie/omsorg, turnus",
            "expression": [
              "",
              "",
              "CALCULATE([Årsverk alt],",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Kvinner og menn\"),",
              "    FILTER(ALL('Kompetansenivå'[Kompetansenivånavn]), [Kompetansenivånavn] = \"Alle\"),",
              "    FILTER(ALL(Sektor[Sektornavn]), [Sektornavn] = \"Helse/pleie/omsorg\"),",
              "    FILTER(ALL(Turnus[Turnusnavn]), [Turnusnavn] = \"Turnus\")",
              ")"
            ]
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    dbo_Region = Source{[Schema=\"dbo\",Item=\"Region\"]}[Data]",
                "in",
                "    dbo_Region"
              ]
            }
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    dbo_Tabeller = Source{[Schema=\"dbo\",Item=\"Tabeller\"]}[Data]",
                "in",
                "    dbo_Tabeller"
              ]
            }
          }
        ]
      },
      {
        "name": "Sektor",
        "columns": [
          {
            "name": "Sektorkode",
            "dataType": "string",
            "sourceColumn": "Sektorkode"
          },
          {
            "name": "Sektornavn",
            "dataType": "string",
            "sourceColumn": "Sektornavn"
          },
          {
            "name": "SektorkodeNavn",
            "dataType": "string",
            "sourceColumn": "SektorkodeNavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    dbo_Sektor = Source{[Schema=\"dbo\",Item=\"Sektor\"]}[Data]",
                "in",
                "    dbo_Sektor"
              ]
            }
          }
        ]
      },
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    dbo_Variabel = Source{[Schema=\"dbo\",Item=\"Variabel\"]}[Data]",
                "in",
                "    dbo_Variabel"
              ]
            }
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    dbo_År = Source{[Schema=\"dbo\",Item=\"År\"]}[Data]",
                "in",
                "    dbo_År"
              ]
            }
          }
        ]
      },
      {
        "name": "Turnus",
        "columns": [
          {
            "name": "Turnuskode",
            "dataType": "string",
            "sourceColumn": "Turnuskode"
          },
          {
            "name": "Turnusnavn",
            "dataType": "string",
            "sourceColumn": "Turnusnavn"
          },
          {
            "name": "TurnuskodeNavn",
            "dataType": "string",
            "sourceColumn": "TurnuskodeNavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"VK-SXD0E-002;Reporting_PAI\",",
                "    dbo_Turnus = Source{[Schema=\"dbo\",Item=\"Turnus\"]}[Data]",
                "in",
                "    dbo_Turnus"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "f55b1254-add9-4ba5-b2d8-c552f827e35c",
        "fromTable": "Alle Data",
        "fromColumn": "Kommunenummer",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "c9f1c408-a2b2-4bf8-a8f3-b95b85b0e22e",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "3efbfa39-ed84-4334-bb3a-bc1870c6395d",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      },
      {
        "name": "329d1e85-f048-4bca-afdc-31491be2d6dd",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "e1de20ed-226e-44d8-9ed9-ea366432ce71",
        "fromTable": "Alle Data",
        "fromColumn": "Sektorkode",
        "toTable": "Sektor",
        "toColumn": "Sektorkode"
      },
      {
        "name": "c271f5b7-030b-4e55-af23-3a4ce3d64599",
        "fromTable": "Alle Data",
        "fromColumn": "Kjønnkode",
        "toTable": "Kjønn",
        "toColumn": "Kjønnkode"
      },
      {
        "name": "0edc0b76-541b-4446-a6dd-72c5be6de3b0",
        "fromTable": "Alle Data",
        "fromColumn": "Kompetansenivåkode",
        "toTable": "Kompetansenivå",
        "toColumn": "Kompetansenivåkode"
      },
      {
        "name": "80dc50fd-8b0d-4f44-9f82-cd82e59c1a90",
        "fromTable": "Alle Data",
        "fromColumn": "Turnuskode",
        "toTable": "Turnus",
        "toColumn": "Turnuskode"
      }
    ],
    "roles": [
      {
        "name": "API",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      },
      {
        "name": "Users",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "I04\\VK.DB.VK-SXD0E-002_PAI.DBO",
            "memberId": "S-1-5-21-2036031588-730629661-1306914269-1033620"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}